/**
 * Builds the small PowerShell hand-off used after Electron exits.
 *
 * Keeping it separate from updater.ts makes the safety-critical behavior easy
 * to test without importing Electron in Vitest's plain Node environment.
 */
export function buildUpdateHelperScript(): string {
  return [
    'param(',
    '  [int]$LeagueVidProcessId,',
    '  [string]$InstallerPath,',
    '  [string]$AppPath,',
    '  [string]$InstallDirectory,',
    '  [string]$ResultPath,',
    '  [string]$LogPath',
    ')',
    "$ErrorActionPreference = 'Stop'",
    "$success = $false",
    "$message = 'The update did not finish.'",
    '$updateTemp = $InstallDirectory + \'.__leaguevid_update_temp\'',
    '',
    'function Write-UpdateLog([string]$Text) {',
    '  Add-Content -LiteralPath $LogPath -Value ((Get-Date).ToUniversalTime().ToString(\'o\') + \' \' + $Text) -Encoding UTF8',
    '}',
    '',
    'try {',
    "  Set-Content -LiteralPath $LogPath -Value 'LeagueVid update helper started.' -Encoding UTF8",
    '  if (-not (Test-Path -LiteralPath $InstallerPath -PathType Leaf)) {',
    "    throw 'The downloaded installer could not be found.'",
    '  }',
    '',
    '  Wait-Process -Id $LeagueVidProcessId -ErrorAction SilentlyContinue',
    '',
    '  $processName = [IO.Path]::GetFileNameWithoutExtension($AppPath)',
    '  for ($attempt = 0; $attempt -lt 150; $attempt++) {',
    '    $remaining = @(',
    '      Get-Process -Name $processName -ErrorAction SilentlyContinue |',
    '        Where-Object { $_.Path -eq $AppPath }',
    '    )',
    '    if ($remaining.Count -eq 0) { break }',
    '    Start-Sleep -Milliseconds 100',
    '  }',
    '  if ($remaining.Count -gt 0) {',
    "    throw 'LeagueVid did not finish closing within 15 seconds.'",
    '  }',
    '',
    '  # electron-builder stages an old installation through the temp drive.',
    '  # Put that staging area beside a custom installation so an H: install',
    '  # is never asked to perform an impossible atomic rename through C:.',
    '  New-Item -ItemType Directory -Path $updateTemp -Force | Out-Null',
    '  $env:TEMP = $updateTemp',
    '  $env:TMP = $updateTemp',
    '',
    "  Write-UpdateLog ('Starting installer in ' + $InstallDirectory)",
    '  # The installer reads the existing custom directory from its registry',
    '  # entry. Passing /D here is unsafe because Start-Process can split a',
    '  # directory containing spaces into a different path.',
    '  $arguments = @(\'/S\', \'/currentuser\', \'--force-run\')',
    '  $installer = Start-Process -FilePath $InstallerPath -ArgumentList $arguments -Wait -PassThru -WindowStyle Hidden',
    "  Write-UpdateLog ('Installer exit code: ' + $installer.ExitCode)",
    '  if ($installer.ExitCode -ne 0) {',
    "    throw ('The installer exited with code ' + $installer.ExitCode + '.')",
    '  }',
    '',
    '  $success = $true',
    "  $message = 'The update was installed successfully.'",
    '} catch {',
    "  $message = 'The update could not be installed: ' + $_.Exception.Message + ' Details: ' + $LogPath",
    '  try { Write-UpdateLog $message } catch {}',
    '} finally {',
    '  try {',
    '    $result = [ordered]@{',
    '      success = $success',
    '      message = $message',
    "      finishedAt = (Get-Date).ToUniversalTime().ToString('o')",
    '    }',
    '    $json = $result | ConvertTo-Json -Compress',
    '    [IO.File]::WriteAllText($ResultPath, $json, [Text.UTF8Encoding]::new($false))',
    '  } catch {',
    "    try { Write-UpdateLog ('Could not save update result: ' + $_.Exception.Message) } catch {}",
    '  }',
    '',
    '  # Reopen even after failure so the user sees the result instead of being',
    '  # left with an app that silently disappeared.',
    '  try {',
    "    Start-Process -FilePath $AppPath -ArgumentList '--updated'",
    '  } catch {',
    "    try { Write-UpdateLog ('Could not reopen LeagueVid: ' + $_.Exception.Message) } catch {}",
    '  }',
    '',
    '  try { Remove-Item -LiteralPath $updateTemp -Recurse -Force -ErrorAction SilentlyContinue } catch {}',
    '  Remove-Item -LiteralPath $PSCommandPath -Force -ErrorAction SilentlyContinue',
    '}'
  ].join('\r\n')
}
